export const LIST_CHANGES = {
  REQUEST: 'LIST_CHANGES_REQUEST',
  SUCCESS: 'LIST_CHANGES_SUCCESS',
  ERROR: 'LIST_CHANGES_ERROR',
};

export const COMMIT_CHANGES = {
  REQUEST: 'COMMIT_CHANGES_REQUEST',
  SUCCESS: 'COMMIT_CHANGES_SUCCESS',
  ERROR: 'COMMIT_CHANGES_ERROR',
};
