export const LIST_DATA_SETS = {
  REQUEST: 'LIST_DATA_SETS_REQUEST',
  SUCCESS: 'LIST_DATA_SETS_SUCCESS',
  ERROR: 'LIST_DATA_SETS_ERROR',
};

export const CREATE_DATA_SET = {
  REQUEST: 'CREATE_DATA_SET_REQUEST',
  SUCCESS: 'CREATE_DATA_SET_SUCCESS',
  ERROR: 'CREATE_DATA_SET_ERROR',
};

export const GET_DATA_SET_DETAIL = {
  REQUEST: 'GET_DATA_SET_DETAIL_REQUEST',
  SUCCESS: 'GET_DATA_SET_DETAIL_SUCCESS',
  ERROR: 'GET_DATA_SET_DETAIL_ERROR',
};

export const GET_FEATURE_DETAIL = {
  REQUEST: 'GET_FEATURE_DETAIL_REQUEST',
  SUCCESS: 'GET_FEATURE_DETAIL_SUCCESS',
  ERROR: 'GET_FEATURE_DETAIL_ERROR',
};

export const HIGHLIGHT_FEATURE = 'HIGHLIGHT_FEATURE';

export const OPEN_FEATURE = 'OPEN_FEATURE';

export const UPDATE_FEATURE_PROPERTIES = {
  REQUEST: 'UPDATE_FEATURE_PROPERTIES_REQUEST',
  SUCCESS: 'UPDATE_FEATURE_PROPERTIES_SUCCESS',
  ERROR: 'UPDATE_FEATURE_PROPERTIES_ERROR',
};
