export const GET_FILE_LIST = {
  INIT: 'GET_FILE_LIST_INIT',
  REQUEST: 'GET_FILE_LIST_REQUEST',
  SUCCESS: 'GET_FILE_LIST_SUCCESS',
  ERROR: 'GET_FILE_LIST_ERROR',
};

export const SELECT_FILE = 'SELECT_FILE';

export const SELECT_TAB = 'SELECT_TAB';

export const TOGGLE_FILE_UPLOADER = 'TOGGLE_FILE_UPLOADER';

export const UPLOAD_FILES = {
  INIT: 'UPLOAD_FILES_INIT',
  REQUEST: 'UPLOAD_FILES_REQUEST',
  SUCCESS: 'UPLOAD_FILES_SUCCESS',
  ERROR: 'UPLOAD_FILES_ERROR',
};

export const TOGGLE_FILE_EDITOR = 'TOGGLE_FILE_EDITOR';

export const UPDATE_FILE = {
  INIT: 'UPDATE_FILE_INIT',
  REQUEST: 'UPDATE_FILE_REQUEST',
  SUCCESS: 'UPDATE_FILE_SUCCESS',
  ERROR: 'UPDATE_FILE_ERROR',
};

export const DELETE_FILES = {
  INIT: 'DELETE_FILES_INIT',
  REQUEST: 'DELETE_FILES_REQUEST',
  SUCCESS: 'DELETE_FILES_SUCCESS',
  ERROR: 'DELETE_FILES_ERROR',
};
