export const GET_IMAGE_LIST = {
  INIT: 'GET_IMAGE_LIST_INIT',
  REQUEST: 'GET_IMAGE_LIST_REQUEST',
  SUCCESS: 'GET_IMAGE_LIST_SUCCESS',
  ERROR: 'GET_IMAGE_LIST_ERROR',
};

export const SELECT_IMAGE = 'SELECT_IMAGE';

export const TOGGLE_IMAGE_UPLOADER = 'TOGGLE_IMAGE_UPLOADER';

export const UPLOAD_IMAGES = {
  INIT: 'UPLOAD_IMAGES_INIT',
  REQUEST: 'UPLOAD_IMAGES_REQUEST',
  SUCCESS: 'UPLOAD_IMAGES_SUCCESS',
  ERROR: 'UPLOAD_IMAGES_ERROR',
};

export const TOGGLE_IMAGE_EDITOR = 'TOGGLE_IMAGE_EDITOR';

export const UPDATE_IMAGE = {
  INIT: 'UPDATE_IMAGE_INIT',
  REQUEST: 'UPDATE_IMAGE_REQUEST',
  SUCCESS: 'UPDATE_IMAGE_SUCCESS',
  ERROR: 'UPDATE_IMAGE_ERROR',
};

export const DELETE_IMAGES = {
  INIT: 'DELETE_IMAGES_INIT',
  REQUEST: 'DELETE_IMAGES_REQUEST',
  SUCCESS: 'DELETE_IMAGES_SUCCESS',
  ERROR: 'DELETE_IMAGES_ERROR',
};
