export const LIST_TOURS = {
  REQUEST: 'LIST_TOURS_REQUEST',
  SUCCESS: 'LIST_TOURS_SUCCESS',
  ERROR: 'LIST_TOURS_ERROR',
};
export const OPEN_TOUR = {
  REQUEST: 'OPEN_TOUR_REQUEST',
  SUCCESS: 'OPEN_TOUR_SUCCESS',
  ERROR: 'OPEN_TOUR_ERROR',
};

export const CREATE_TOUR = {
  REQUEST: 'CREATE_TOUR_REQUEST',
  SUCCESS: 'CREATE_TOUR_SUCCESS',
  ERROR: 'CREATE_TOUR_ERROR',
};

export const CREATE_TOUR_STEP = {
  REQUEST: 'CREATE_TOUR_STEP_REQUEST',
  SUCCESS: 'CREATE_TOUR_STEP_SUCCESS',
  ERROR: 'CREATE_TOUR_STEP_ERROR',
};

export const UPDATE_TOUR_STEP = {
  REQUEST: 'UPDATE_TOUR_STEP_REQUEST',
  SUCCESS: 'UPDATE_TOUR_STEP_SUCCESS',
  ERROR: 'UPDATE_TOUR_STEP_ERROR',
};

export const DELETE_TOUR_STEP = {
  REQUEST: 'DELETE_TOUR_STEP_REQUEST',
  SUCCESS: 'DELETE_TOUR_STEP_SUCCESS',
  ERROR: 'DELETE_TOUR_STEP_ERROR',
};

export const REORDER_TOUR_STEPS = {
  REQUEST: 'REORDER_TOUR_STEPS_REQUEST',
  SUCCESS: 'REORDER_TOUR_STEPS_SUCCESS',
  ERROR: 'REORDER_TOUR_STEPS_ERROR',
};

// This action is synchronous
export const CHANGE_ACTIVE_TOUR_STEP = 'CHANGE_ACTIVE_TOUR_STEP';

export const CREATE_MARKER = {
  REQUEST: 'CREATE_MARKER_REQUEST',
  SUCCESS: 'CREATE_MARKER_SUCCESS',
  ERROR: 'CREATE_MARKER_ERROR',
};

export const DELETE_MARKER = {
  REQUEST: 'DELETE_MARKER_STEP_REQUEST',
  SUCCESS: 'DELETE_MARKER_SUCCESS',
  ERROR: 'DELETE_MARKER_ERROR',
};

export const UPDATE_MARKER = {
  REQUEST: 'UPDATE_MARKER_REQUEST',
  SUCCESS: 'UPDATE_MARKER_SUCCESS',
  ERROR: 'UPDATE_MARKER_ERROR',
};

export const CLOSE_OPEN_TOUR = 'CLOSE_OPEN_TOUR';
