export const LIST_TOURS = { SUCCESS: 'LIST_TOURS_SUCCESS', ERROR: 'LIST_TOURS_ERROR' };
export const OPEN_TOUR = { SUCCESS: 'OPEN_TOUR_SUCCESS', ERROR: 'OPEN_TOUR_ERROR' };

export const CREATE_TOUR = { SUCCESS: 'CREATE_TOUR_SUCCESS', ERROR: 'CREATE_TOUR_ERROR' };

export const CREATE_TOUR_STEP = { SUCCESS: 'CREATE_TOUR_STEP_SUCCESS', ERROR: 'CREATE_TOUR_STEP_ERROR' };
export const UPDATE_TOUR_STEP = { SUCCESS: 'UPDATE_TOUR_STEP_SUCCESS', ERROR: 'UPDATE_TOUR_STEP_ERROR' };
export const DELETE_TOUR_STEP = { SUCCESS: 'DELETE_TOUR_STEP_SUCCESS', ERROR: 'DELETE_TOUR_STEP_ERROR' };
export const REORDER_TOUR_STEPS = { SUCCESS: 'REORDER_TOUR_STEPS_SUCCESS', ERROR: 'REORDER_TOUR_STEPS_ERROR' };

export const CREATE_MARKER = { SUCCESS: 'CREATE_MARKER_SUCCESS', ERROR: 'CREATE_MARKER_ERROR' };
export const DELETE_MARKER = { SUCCESS: 'DELETE_MARKER_SUCCESS', ERROR: 'DELETE_MARKER_ERROR' };
export const UPDATE_MARKER = { SUCCESS: 'UPDATE_MARKER_SUCCESS', ERROR: 'UPDATE_MARKER_ERROR' };
