export const LOGIN_USER = {
  REQUEST: 'LOGIN_USER_REQUEST',
  SUCCESS: 'LOGIN_USER_SUCCESS',
  ERROR: 'LOGIN_USER_ERROR',
};

export const REGISTER_USER = {
  REQUEST: 'REGISTER_USER_REQUEST',
  SUCCESS: 'REGISTER_USER_SUCCESS',
  ERROR: 'REGISTER_USER_ERROR',
};

export const USER_DETAIL = {
  REQUEST: 'USER_DETAIL_REQUEST',
  SUCCESS: 'USER_DETAIL_SUCCESS',
  ERROR: 'USER_DETAIL_ERROR',
};

export const GET_USER_STATISTICS = {
  REQUEST: 'GET_USER_STATISTICS_REQUEST',
  SUCCESS: 'GET_USER_STATISTICS_SUCCESS',
  ERROR: 'GET_USER_STATISTICS_ERROR',
};

export const LOGOUT_USER = 'LOGOUT_USER';
