export const LIST_ITEMS = {
  REQUEST: 'LIST_ITEMS_REQUEST',
  SUCCESS: 'LIST_ITEMS_SUCCESS',
  ERROR: 'LIST_ITEMS_ERROR',
};

export const BUILD_FORM = {
  INIT: 'BUILD_FORM_INIT',
  REQUEST: 'BUILD_FORM_REQUEST',
  SUCCESS: 'BUILD_FORM_SUCCESS',
  ERROR: 'BUILD_FORM_ERROR',
};

export const GET_RELATED_FIELDS = {
  REQUEST: 'GET_RELATED_FIELDS_REQUEST',
  SUCCESS: 'GET_RELATED_FIELDS_SUCCESS',
  ERROR: 'GET_RELATED_FIELDS_ERROR',
};

export const UPDATE_BASIC_FIELDS = {
  REQUEST: 'UPDATE_BASIC_FIELDS_REQUEST',
  SUCCESS: 'UPDATE_BASIC_FIELDS_SUCCESS',
  ERROR: 'UPDATE_BASIC_FIELDS_ERROR',
};

export const UPDATE_RELATED_FIELD = {
  REQUEST: 'UPDATE_RELATED_FIELD_REQUEST',
  SUCCESS: 'UPDATE_RELATED_FIELD_SUCCESS',
  ERROR: 'UPDATE_RELATED_FIELD_ERROR',
};
