export const LIST_ITEMS = {
  REQUEST: 'LIST_ITEMS_REQUEST',
  SUCCESS: 'LIST_ITEMS_SUCCESS',
  ERROR: 'LIST_ITEMS_ERROR',
};

export const GET_ITEM_DETAIL = {
  INIT: 'GET_ITEM_DETAIL_INIT',
  REQUEST: 'GET_ITEM_DETAIL_REQUEST',
  SUCCESS: 'GET_ITEM_DETAIL_SUCCESS',
  ERROR: 'GET_ITEM_DETAIL_ERROR',
};

export const DELETE_ITEM = {
  INIT: 'DELETE_ITEM_INIT',
  REQUEST: 'DELETE_ITEM_REQUEST',
  SUCCESS: 'DELETE_ITEM_SUCCESS',
  ERROR: 'DELETE_ITEM_ERROR',
};

export const BUILD_FORM = {
  INIT: 'BUILD_FORM_INIT',
  REQUEST: 'BUILD_FORM_REQUEST',
  SUCCESS: 'BUILD_FORM_SUCCESS',
  ERROR: 'BUILD_FORM_ERROR',
};

export const GET_RELATED_FIELDS = {
  REQUEST: 'GET_RELATED_FIELDS_REQUEST',
  SUCCESS: 'GET_RELATED_FIELDS_SUCCESS',
  ERROR: 'GET_RELATED_FIELDS_ERROR',
};

export const UPDATE_BASIC_FIELDS = {
  REQUEST: 'UPDATE_BASIC_FIELDS_REQUEST',
  SUCCESS: 'UPDATE_BASIC_FIELDS_SUCCESS',
  ERROR: 'UPDATE_BASIC_FIELDS_ERROR',
};

export const UPDATE_RELATED_FIELDS = {
  REQUEST: 'UPDATE_RELATED_FIELDS_REQUEST',
  SUCCESS: 'UPDATE_RELATED_FIELDS_SUCCESS',
  ERROR: 'UPDATE_RELATED_FIELDS_ERROR',
};

export const SEARCH_RELATED_FIELDS = {
  INIT: 'SEARCH_RELATED_FIELDS_INIT',
  REQUEST: 'SEARCH_RELATED_FIELDS_REQUEST',
  SUCCESS: 'SEARCH_RELATED_FIELDS_SUCCESS',
  ERROR: 'SEARCH_RELATED_FIELDS_ERROR',
};

export const PUBLISH_WORKSHOP_CONTENT = {
  INIT: 'PUBLISH_WORKSHOP_CONTENT_INIT',
  REQUEST: 'PUBLISH_WORKSHOP_CONTENT_REQUEST',
  SUCCESS: 'PUBLISH_WORKSHOP_CONTENT_SUCCESS',
  ERROR: 'PUBLISH_WORKSHOP_CONTENT_ERROR',
};

export const BUILD_FINDER = {
  INIT: 'BUILD_FINDER_INIT',
  REQUEST: 'BUILD_FINDER_REQUEST',
  SUCCESS: 'BUILD_FINDER_SUCCESS',
  ERROR: 'BUILD_FINDER_ERROR',
};

export const GET_INSTANCE_LIST = {
  INIT: 'GET_INSTANCE_LIST_INIT',
  REQUEST: 'GET_INSTANCE_LIST_REQUEST',
  SUCCESS: 'GET_INSTANCE_LIST_SUCCESS',
  ERROR: 'GET_INSTANCE_LIST_ERROR',
};

export const GET_LOCATION_PICKER_DATA_SET = {
  INIT: 'GET_LOCATION_PICKER_DATA_SET_INIT',
  REQUEST: 'GET_LOCATION_PICKER_DATA_SET_REQUEST',
  SUCCESS: 'GET_LOCATION_PICKER_DATA_SET_SUCCESS',
  ERROR: 'GET_LOCATION_PICKER_DATA_SET_ERROR',
};

export const TOGGLE_LOCATION_PICKER = 'TOGGLE_LOCATION_PICKER';

export const SELECT_POSITION = 'SELECT_POSITION';

export const SAVE_POSITION = 'SAVE_POSITION';

export const TOGGLE_RELATED_CONTENT_FINDER = 'TOGGLE_RELATED_CONTENT_FINDER';

export const TOGGLE_MEDIA_CENTER = 'TOGGLE_MEDIA_CENTER';

export const UPDATE_MEDIA_RELATIONSHIPS = {
  INIT: 'UPDATE_MEDIA_RELATIONSHIPS_INIT',
  REQUEST: 'UPDATE_MEDIA_RELATIONSHIPS_REQUEST',
  SUCCESS: 'UPDATE_MEDIA_RELATIONSHIPS_SUCCESS',
  ERROR: 'UPDATE_MEDIA_RELATIONSHIPS_ERROR',
};

export const UPDATE_MEDIA_ORDER = {
  INIT: 'UPDATE_MEDIA_ORDER_INIT',
  REQUEST: 'UPDATE_MEDIA_ORDER_REQUEST',
  SUCCESS: 'UPDATE_MEDIA_ORDER_SUCCESS',
  ERROR: 'UPDATE_MEDIA_ORDER_ERROR',
};
